# Generated by Django 4.2.3 on 2023-07-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название блога')),
                ('description', models.TextField(verbose_name='Информация о блоге')),
                ('image', models.ImageField(upload_to='blog_image/', verbose_name='Картинка для блога')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата создание')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL адрес блога')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название категорий блога')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL адрес категорий')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категорий',
            },
        ),
        migrations.CreateModel(
            name='BlogTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название тэг для блога')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL адрес категорий')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='CommentBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
            ],
        ),
    ]
