# Generated by Django 4.2.3 on 2023-07-08 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название категорий блога')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL адрес категорий')),
            ],
        ),
        migrations.CreateModel(
            name='BlogTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название тэг для блога')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL адрес категорий')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название блога')),
                ('description', models.TextField(blank=True, verbose_name='Информация о блоге')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата создание')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL адрес блога')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='blog.blogcategory', verbose_name='Категория')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='blog.blogtags', verbose_name='Тэг')),
            ],
        ),
    ]
