version: '3.5'

services:
  db:
    container_name: db_container
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - /postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

