version: "3.9"

services:
  postgres:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:6
    env_file:
      - .env
    ports:
      - "5050:5050"

volumes:
  data: