# Generated by Django 4.2.3 on 2023-07-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='main_pictures/', verbose_name='Основное изображение товара'),
        ),
    ]
