# Generated by Django 4.2.3 on 2023-07-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='product_image/', verbose_name='Основное изображение товара'),
        ),
    ]
